### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/admin-iot-devices#29]
Forslag til rettelser i UI til at forbedre UX:

```[tasklist]
### Tasks
- [x] Skjul seneste import/export for skabeloner
- [x] Flyt "Ny måler" til "Start", og fjern oprindelig "Start"
- [x] Forbedr device added confirmation (skjul seneste data + tilføj navne til yderligere registrerede enheder + template navn)
- [ ] https://github.com/Randers-Kommune-Digitalisering/admin-iot-devices/issues/52
```
