### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/admin-iot-devices#69]
```[tasklist]
### Tasks
- [x] Vent med at farve kanten på inputbokse hvis der ikke er ændret i data
- [x] Lås eksport-enhed for enheder som ikke kan konverteres (%, pcs)
- [x] Fast sortering af målepunkter (ændres pt. tilfældigt)
- [ ] Automatisk scrolling til listeelement med "returnfrom" parameter
```
